name: 'Get Git Log Action'
description: 'Get git log from specify git tag to the present'
author: 'JantHsueh'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  type:
    description: 'Specify git log or git tag'
    required: false
  id:
    description: 'Specify commitID or tagName'
    required: false
outputs:
  log:
    description: 'git logs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.id }}
